[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["Dmitry Yarinsky"]

[project]
name = "hexlet-code"
version = "0.1.0"
dependencies = [
    "Flask==3.0.0",
    "gunicorn==21.2.0",
    "python-dotenv==1.0.0",
]